# Project Information
site_name: 个人博客
site_description: 算法
site_author: 潘超
site_url: https://chaopan95.github.io/blogs/

# Copyright
copyright: 'Copyright &copy; 2021 Chao PAN'

# theme
theme:
    name: material
    palette:
        primary: 'White'
        accent: 'Red'
    include_search_page: false
    search_index_only: true
    feature:
        tabs: true
    language: 'zh'
    font:
        text: 'Fira Sans'
        code: 'Fira Mono'
    favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
    - 介绍: index.md
    - 算法:
        - 剑指offer: algo/jsoffer.md
        - 动态规划:
            - 基础: algo/dp/basis.md
            - 划分区间: algo/dp/segment.md
            - 背包问题: algo/dp/knapsack.md
            - 最长递增子序列: algo/dp/lis.md
            - 路径问题: algo/dp/path.md
            - 矩阵问题: algo/dp/matrix.md
            - 股票买卖: algo/dp/stocks.md
            - 最长公共子序列: algo/dp/lcs.md
            - 编辑距离: algo/dp/edit-distance.md
            - 打家劫舍: algo/dp/rob.md
            - 序列型: algo/dp/sequence.md
            - 区间型: algo/dp/interval.md
            - 左右遍历型: algo/dp/left-right-traversal.md
            - 数位型: algo/dp/digits.md
        - 贪心: algo/greedy.md
        - 二分查找: algo/binary-search.md
        - 双指针: algo/two-pointers.md
        - 搜索: algo/search.md
        - 前缀和: algo/prefix-sum.md
        - 数学: algo/math.md
        - 矩阵: algo/matrix.md
        - Leetcode: algo/leetcode.md
    - 数据结构:
        - 链表: data-structure/list.md
        - 栈 & 队列: data-structure/stack-queue.md
        - 单调栈: data-structure/monotone-stack.md
        - 单调队列: data-structure/monotone-queue.md
        - 树:
            - 基础: data-structure/tree/basis.md
            - 二叉树: data-structure/tree/binary-tree.md
            - 遍历: data-structure/tree/traversal.md
            - 前缀树: data-structure/tree/prefix-tree.md
        - 字符串: data-structure/string.md
        - 并查集: data-structure/unionset.md
        - 树状数组: data-structure/binary-indexed-tree.md
        - 线段树: data-structure/segment-tree.md
        - 优先队列: data-structure/priority-queue.md
        - 哈希表: data-structure/hash.md
    - 机器学习:
        - 决策树: machine-learning/decision-tree.md
        - ROC: machine-learning/roc.md
    - 概率&统计:
        - 概率: probability/prob.md
