# Project Information
site_name: 个人博客
site_description: 算法
site_author: 潘超
site_url: https://chaopan95.github.io/blogs/
strict: true

# Copyright
copyright: 'Copyright &copy; 2021 Chao PAN'
google_analytics:
  - 'UA-124485594-1'
  - 'auto'

# theme
theme:
    name: material
    palette:
        primary: 'White'
        accent: 'Red'
    include_search_page: false
    search_index_only: true
    feature:
        tabs: true
    language: 'zh'
    font:
        text: 'Fira Sans'
        code: 'Fira Mono'
    favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
    - 介绍: intro.md
    - 算法:
        - 剑指offer: algo/jsoffer.md
        - 动态规划: algo/动态规划.md
    - 数据结构:
        - 字符串:
            - 匹配: data-structure/string/match.md
